services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hms_application:latest
    ports:
      - "5173:5173"
    volumes:
      - hms_vol:/app             
      - /app/node_modules       
    container_name: hms_container
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  hms_vol:                       