services:
  backend:
    build: ./backend
    ports:
      - "4451:4451"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
